steps:
  - label: "Ascend NPU Test"
    soft_fail: true
    depends_on: ~
    agents:
      queue: "ascend"
    command: bash .buildkite/scripts/hardware_ci/run-npu-test.sh
    timeout_in_minutes: 20
    env:
      BUILDKITE_CLEAN_CHECKOUT: true
